# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POME-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for POME-iOS
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  pod 'Alamofire'
  pod 'FSCalendar'

end
